# Three Dimensional

In [17]:
import gpytorch
import torch

import numpy as np
from numpy.random import multivariate_normal

import pandas as pd

import plotly
import plotly.graph_objects as go
import plotly.express as px


from scipy.stats import norm

import csv

In [18]:
x, y = torch.meshgrid(torch.linspace(0, 1, 10), torch.linspace(0, 1, 10), indexing="ij")
X = train_x = torch.cat((
    x.contiguous().view(x.numel(), 1),
    y.contiguous().view(y.numel(), 1)),
    dim=1
)
z = -(X[:, 1]*np.sin(X[:, 1] + X[:, 0]/2)-(X[:, 0])*np.sin(X[:, 0]+47))
print(X.size())
print(y.size())

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, kernel):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(kernel)
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

def gpytorchOptimize(xAxis, yPoints, kernel):
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = ExactGPModel(xAxis, yPoints, likelihood, kernel)
    model.train()
    likelihood.train()

    # Use the adam optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

    # "Loss" for GPs - the marginal log likelihood
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    for i in range(10):
        optimizer.zero_grad()
        output = model(xAxis)
        loss = -mll(output, yPoints)
        loss.backward()
        optimizer.step()

    model.eval()
    observedPred = likelihood(model(xAxis))
    prediction = observedPred.mean.detach().numpy()
    

    return prediction

torch.Size([100, 2])
torch.Size([10, 10])


In [19]:
# kernel = gpytorch.kernels.MaternKernel(nu=0.5, ard_num_dims = 2)
# prediction = gpytorchOptimize(X, z, kernel)
x, y = torch.meshgrid(torch.linspace(0, 100, 20), torch.linspace(0, 100, 20), indexing="ij")
X = train_x = torch.cat((
    x.contiguous().view(x.numel(), 1),
    y.contiguous().view(y.numel(), 1)),
    dim=1
)
print(X)
def f(x1, x2):
    return (-x2+47)*np.sin(np.sqrt(x2+x1/2+47))-x1*np.sin(np.sqrt(x1-x2+47))
xResult = []
yResult = []
z =[]
for item in X:
    x = item[0].item()
    y = item[1].item()
    xResult.append(item[0].item())
    yResult.append(item[1].item())
    z.append(f(x, y))
    
# fig = go.Figure(data = go.Scatter3d(x = np.array(xResult), y = np.array(yResult), z = prediction, mode = "markers"))
# fig.show()

fig2 = go.Figure(data = go.Scatter3d(x = np.array(xResult), y = np.array(yResult), z = np.array(z), mode = "markers"))
fig2.show()

tensor([[  0.0000,   0.0000],
        [  0.0000,   5.2632],
        [  0.0000,  10.5263],
        [  0.0000,  15.7895],
        [  0.0000,  21.0526],
        [  0.0000,  26.3158],
        [  0.0000,  31.5789],
        [  0.0000,  36.8421],
        [  0.0000,  42.1053],
        [  0.0000,  47.3684],
        [  0.0000,  52.6316],
        [  0.0000,  57.8947],
        [  0.0000,  63.1579],
        [  0.0000,  68.4211],
        [  0.0000,  73.6842],
        [  0.0000,  78.9474],
        [  0.0000,  84.2105],
        [  0.0000,  89.4737],
        [  0.0000,  94.7368],
        [  0.0000, 100.0000],
        [  5.2632,   0.0000],
        [  5.2632,   5.2632],
        [  5.2632,  10.5263],
        [  5.2632,  15.7895],
        [  5.2632,  21.0526],
        [  5.2632,  26.3158],
        [  5.2632,  31.5789],
        [  5.2632,  36.8421],
        [  5.2632,  42.1053],
        [  5.2632,  47.3684],
        [  5.2632,  52.6316],
        [  5.2632,  57.8947],
        [  5.2632,  63.1579],
        [ 

C:\Users\WONBIN~1\AppData\Local\Temp/ipykernel_25468/3979157913.py:11: RuntimeWarning:

invalid value encountered in sqrt



In [20]:
i = -1.5
xData = []
yData = []
counter = 0

def f(x):
    return x**2+np.cos(x**2)+np.sin(x**3)

while (i <= 1.5):
    for x in range(8):
        xData.append(i)
    yData.append(f(i))
    yData.append(f(i+i/16))
    yData.append(f(i+i/18))
    yData.append(f(i+i/21))
    yData.append(f(i)*0.9)
    yData.append(f(i+i/16)*1.1)
    yData.append(f(i+i/18)*0.85)
    yData.append(f(i+i/20)*1.17)
    
    i+=0.1
    
xData = np.array(xData)
yData = np.array(yData)


for i in range(len(xData)):
    if (i >= len(xData)):
        break
    elif (i%3 == 0):
        xData = np.delete(xData, i)
        yData = np.delete(yData, i)
    elif (i%5 == 0):
        xData = np.delete(xData, [i, i+3])
        yData = np.delete(yData, [i, i+3])
    elif (i%5 == 0):
        xData = np.delete(xData, i)
        yData = np.delete(yData, i)

    
def remove(start, end, xData, yData):
    x = start
    array = []
    while (x < end):
        array.append(x)
        x+=1
    
    xData = np.delete(xData, array)
    yData = np.delete(yData, array)
    
    return xData, yData

xData, yData = remove(30, 35, xData, yData)
xData, yData = remove(50, 55, xData, yData)
xData, yData = remove(70, 80, xData, yData)
xData, yData = remove(100, 110, xData, yData)

print(len(xData))
fig = go.Figure(go.Scatter(x = xData, y = yData, mode = "markers"))
fig.show()

120


In [21]:
def csvReader(filename):
    file = open(filename, 'r')
    rows = list(csv.reader(file, delimiter = ","))
    rows.pop(0)
    x1 = []
    x2 = []
    y = []
    for row in rows:
        x1.append(float(row[0]))
        x2.append(float(row[1]))
        y.append(float(row[2]))

    return torch.tensor(x1), torch.tensor(x2), torch.tensor(y)

x1, x2, y = csvReader("testdata/3dtest.csv")

In [124]:
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, kernel):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(kernel)
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

class Optimizer:
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.numInput = self.X.size(0)
        self.params = self.X.dim()
        print(self.params)
        if len(self.X != 0):
            if self.params == 1:
                self.domain = [self.X[0].item(), self.X[-1].item()]
                self.range = self.domain[1]-self.domain[0]
            elif self.params == 2:
                self.domain = [[self.X[0][0].item(), self.X[-1][0].item()], [self.X[0][1].item(), self.X[-1][1].item()]]
                self.range1 = self.domain[0][1]-self.domain[0][0]
                self.range2 = self.domain[1][1]-self.domain[1][0]
    def run(self):
        self.trainGP()
        for i in range(5):
            self.modelSurrogate()
            self.evaluateNext()
        return self.plot()

    def setOptimizationTarget(self, target):
        if target == "Maximize":
            self.target = max
            self.targetIndex = np.argmax
        else:
            self.target = min
            self.targetIndex = np.argmin
    
    def setKernel(self, kernelInput):
        self.kernel = gpytorch.kernels.MaternKernel(nu=0.5, ard_nums = 1)
        if kernelInput == "matern":
            self.kernel = gpytorch.kernels.MaternKernel(nu=0.5, ard_nums = 1) 
        if kernelInput == "sek":
            self.kernel = gpytorch.kernels.RBFKernel()  

    def setAcquisition(self, acquisitionInput):
        self.acquisition = self.probabilityOfImprovement 
        if acquisitionInput == "pi":
            self.acquisition = self.probabilityOfImprovement 
        
    def trainGP(self, trainIter = 10):
        self.likelihood = gpytorch.likelihoods.GaussianLikelihood()
        self.model = ExactGPModel(self.X, self.y, self.likelihood, self.kernel)
        mll = gpytorch.mlls.ExactMarginalLogLikelihood(self.likelihood, self.model)

        self.model.train()
        self.likelihood.train()

        optimizer = torch.optim.Adam(self.model.parameters(), lr=0.1)
        for i in range(trainIter):
            optimizer.zero_grad()
            output = self.model(self.X)
            loss = -mll(output, self.y)
            loss.backward()
            optimizer.step()

        self.model.eval()
        self.observedPred = (self.model(self.X))
    
    def modelSurrogate(self):
        self.prediction = self.likelihood(self.observedPred).mean.detach().numpy()

    def probabilityOfImprovement(self):
        if self.params == 1:
            exploreX = self.range*torch.rand(25)+self.domain[0]
            bestPoint = self.target(self.prediction)
            observedPred = (self.model(exploreX))
            exploreY = self.likelihood(observedPred).mean.detach().numpy()
            stdev = np.sqrt(observedPred.variance.detach().numpy())
            z = (exploreY - bestPoint)/stdev
            cdf = norm.cdf(z)
            if self.target == max:
                index = np.argmax(cdf)
            else:
                cdf = -cdf
                index = np.argmin(cdf)
                newX = exploreX[index]

            return newX.double(), torch.tensor([index])
        elif self.params == 2:
            exploreX1 = self.range1*torch.rand(int(5))+self.domain[0][0]
            exploreX2 = self.range2*torch.rand(int(5))+self.domain[1][0]
            exploreX = torch.cat((
                exploreX1.contiguous().view(exploreX1.numel(), 1),
                exploreX2.contiguous().view(exploreX2.numel(), 1)),
                dim=1
            )
            bestPoint = self.target(self.prediction)
            observedPred = (self.model(exploreX))
            exploreY = self.likelihood(observedPred).mean.detach().numpy()
            stdev = np.sqrt(observedPred.variance.detach().numpy())
            z = (exploreY - bestPoint)/stdev
            cdf = norm.cdf(z)
            if self.target == max:
                index = np.argmax(cdf)
            else:
                cdf = -cdf
                index = np.argmin(cdf)
            newX = exploreX[index]
            return newX, index
    def evaluateNext(self):
        if self.params == 1:
            newX, index = self.acquisition()
            self.X.index_add(0, index, newX)
        elif self.params == 2:
            newX, index = self.acquisition()
            print(newX.unsqueeze(0))
            self.X = torch.cat((self.X, newX.unsqueeze(0)), 0)
            print(self.X)
    def plot(self):
        if self.params == 1:
            figure = go.Figure(data = go.Scatter(x = self.X, y = self.prediction, name = "Prediction"))
            figure.add_trace(go.Scatter(x = self.X, y = self.y, name = "Training data", mode= "markers"))
            return figure, _
        elif self.params == 2:
            x1 = []
            x2 = []
            for item in self.X:
                x1.append(item[0].item())
                x2.append(item[1].item())
            figure = go.Figure(data = go.Scatter3d(x = x1, y = x2, z = self.prediction, mode = "markers"))
            figure.show()
            x, y = torch.meshgrid(torch.linspace(self.domain[0][0], self.domain[0][1], 10), torch.linspace(self.domain[1][0], self.domain[-1][1], 10), indexing="ij")
            X = torch.cat((
                x.contiguous().view(x.numel(), 1),
                y.contiguous().view(y.numel(), 1)),
                dim=1
            )
            prediction = self.likelihood(self.model(X)).mean.detach().numpy()
            prediction = prediction.reshape(10, 10)
            figure2 = go.Figure(data = go.Surface(z = prediction, x = x, y = y))
            figure2.show()
    def result(self):
        if self.params == 1:
            if self.target == max:
                index = self.prediction.argmax()
            else:
                index = self.prediction.argmin()
            bestX = self.X[index].item()
            bestY = self.prediction[index]
            bestX = round(bestX, 4)
            bestY = round(bestY, 4)
            if self.target == max:
                result = "Output maximized at param1 value of " + str(bestX) + " for a predicted output of " +  str(bestY)
            else:
                result = "Output minimized at param1 value of " + str(bestX) + " for a predicted output of " +  str(bestY)
            return result
        elif self.params == 2:
            if self.target == max:
                index = self.prediction.argmax()
            else:
                index = self.prediction.argmin()
            bestX1 = self.X[index][0].item()
            bestX2 = self.X[index][1].item()
            bestY = self.prediction[index]
            bestX1 = round(bestX1, 4)
            bestX2 = round(bestX2, 4)
            if self.target == max:
                result = "Output maximized at param1 value of " + str(bestX1) + " and param2 value of " + str(bestX2) + " for a predicted output of " +  str(bestY)
            else:
                result = "Output minimized at param1 value of " + str(bestX1) + " and param2 value of " + str(bestX2) + " for a predicted output of " +  str(bestY)
            return result

In [125]:
## Turn param1 and param2 inputs into torch form that GP can use
X = torch.cat((
    x1.contiguous().view(x1.numel(), 1),
    x2.contiguous().view(x2.numel(), 1)),
    dim=1
)

In [126]:
optimizer = Optimizer(X, y)
optimizer.setOptimizationTarget("Maximize")
optimizer.setKernel("matern")
optimizer.setAcquisition("pi")
optimizer.trainGP()
optimizer.modelSurrogate()
optimizer.run()
optimizer.plot()
print(optimizer.result())

2
tensor([[93.2145, 25.9185]])
tensor([[  0.0000,   0.0000],
        [  0.0000,  11.1111],
        [  0.0000,  22.2222],
        [  0.0000,  33.3333],
        [  0.0000,  44.4444],
        [  0.0000,  55.5556],
        [  0.0000,  66.6667],
        [  0.0000,  77.7778],
        [  0.0000,  88.8889],
        [  0.0000, 100.0000],
        [ 11.1111,   0.0000],
        [ 11.1111,  11.1111],
        [ 11.1111,  22.2222],
        [ 11.1111,  33.3333],
        [ 11.1111,  44.4444],
        [ 11.1111,  55.5556],
        [ 11.1111,  66.6667],
        [ 11.1111,  77.7778],
        [ 11.1111,  88.8889],
        [ 11.1111, 100.0000],
        [ 22.2222,   0.0000],
        [ 22.2222,  11.1111],
        [ 22.2222,  22.2222],
        [ 22.2222,  33.3333],
        [ 22.2222,  44.4444],
        [ 22.2222,  55.5556],
        [ 22.2222,  66.6667],
        [ 22.2222,  77.7778],
        [ 22.2222,  88.8889],
        [ 22.2222, 100.0000],
        [ 33.3333,   0.0000],
        [ 33.3333,  11.1111],
        [

Output maximized at param1 value of 66.6667 and param2 value of 0.0 for a predicted output of 42.64015


In [55]:
X = optimizer.getX()
newX1 = torch.tensor[]